version: "2"
plugins:
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  nodesecurity:
    enabled: true
checks:
  similar-code:
    threshold: 50
exclude_patterns:
  - "dist/"
  - "node_modules/"
  - "test/"
  - "example/"
  - "**.d.ts"
  - "**/*.md"
  - "**/*.config.*"
  - "**/*.conf.*"
