language: node_js
node_js:
  - "10"

before_install:
  - npm i -g npm@latest

install:
  - npm i

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
#  - ./cc-test-reporter before-build

script:
  - npm run test

#after_script:
#  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


before_deploy:
  - npm shrinkwrap
  - npm pack
  - npm install
  - git add .
  - git commit -m "shrinkwrap"

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
