language: node_js
node_js:
  - "10"

before_install:
  - npm i -g npm@latest

install:
  - npm i

script:
  - npm run test

before_deploy:
  - npm shrinkwrap
  - npm pack

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
